version: '3.1'
services:
    frontend:
        image: coveffect-frontend:latest
        build:
            context: ./frontend/
            dockerfile: Dockerfile
        command: sh -c "npm install && quasar dev"
        volumes:
            - ./frontend/:/usr/src/app/
        container_name: coveffect-frontend
        ports:
            - 8082:8080
            # - 8080:8080
    backend:
        # build:
        #     context: ./backend/
        #     dockerfile: Dockerfile
        image: 2603931630/coveffect-backend:latest
        container_name: coveffect-backend
        volumes:
            - ./backend/:/workspace/
        command: sh -c "flask run -p 5003 --host=0.0.0.0"
        ports:
            - 61113:5003
        environment:
            - PYTHONUNBUFFERED=1
    database:
        container_name: coveffect-db
        image: 2603931630/coveffect-db:latest
        environment:
            - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
        secrets:
            - db_root_password
secrets:
    db_root_password:
        file: ./database/secrets/db_root_password.txt
